<a href="https://colab.research.google.com/github/Bavitayadav8/Bavitayadav8/blob/main/D42D43.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Connect your google drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/GUVI/data/Bengaluru_House_Data.csv")

In [ ]:
import numpy as np
df = df.replace(to_replace=np.nan,value = "Three BHK")
print(df)

                  area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size    society total_sqft bath    balcony   price  
0          2 BHK    Coomee        1056  2.0        1.0   39.07  
1    

In [ ]:
!pip install scikit-learn

import numpy as np
from sklearn.impute import SimpleImputer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
imp = SimpleImputer(missing_values = np.nan,strategy="mean")
data = [[1,2],[np.nan,3],[7,6],[7,6],[np.nan,6],[7,6]]
imp.fit_transform(data)

array([[1., 2.],
       [7., 3.],
       [7., 6.],
       [7., 6.],
       [7., 6.],
       [7., 6.]])

## Most Frequent 

In [ ]:
imp = SimpleImputer(missing_values = np.nan,strategy="most_frequent")
data = [[1,2],[np.nan,3],[7,6],[7,6],[np.nan,6],[7,6]]
imp.fit_transform(data)

array([[1., 2.],
       [7., 3.],
       [7., 6.],
       [7., 6.],
       [7., 6.],
       [7., 6.]])

In [ ]:
imp = SimpleImputer(missing_values = np.nan,strategy="constant")
data = [[1,2],[np.nan,3],[7,6],[7,6],[np.nan,6],[7,6]]
imp.fit_transform(data)

array([[1., 2.],
       [0., 3.],
       [7., 6.],
       [7., 6.],
       [0., 6.],
       [7., 6.]])

### **Simple Imputer using Entire DataFrame**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

##### **Read data and perform imputation**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/GUVI/data/Bengaluru_House_Data.csv")
imp = SimpleImputer(missing_values=np.nan,strategy="mean")
df[['bath','balcony']] = imp.fit_transform(df[['bath','balcony']])
print(df)

                  area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath   balcony   price  
0          2 BHK  Coomee        1056   2.0  1.000000   39.07  
1      4 

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/GUVI/data/Bengaluru_House_Data.csv")
imp = SimpleImputer(missing_values=np.nan,strategy="most_frequent")
df['bath'] = imp.fit_transform(df[['bath']])
df = pd.DataFrame(df)
print(df)
print(df.isnull().sum())

                          0              1                         2  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

               3        4     5    6    7      8  
0          2 BHK  Coomee   1056  2.0  1.0  39.07  
1      4 Bedroom  Theanmp  2600  

### ***Label Encoding***

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/GUVI/data/Bengaluru_House_Data.csv")
df['area_type'].unique()

le = LabelEncoder()
df['area_type_encoded'] = le.fit_transform(df['area_type'])
print(df[['area_type','area_type_encoded']].head(20))

               area_type  area_type_encoded
0   Super built-up  Area                  3
1             Plot  Area                  2
2         Built-up  Area                  0
3   Super built-up  Area                  3
4   Super built-up  Area                  3
5   Super built-up  Area                  3
6   Super built-up  Area                  3
7   Super built-up  Area                  3
8   Super built-up  Area                  3
9             Plot  Area                  2
10  Super built-up  Area                  3
11            Plot  Area                  2
12  Super built-up  Area                  3
13        Built-up  Area                  0
14            Plot  Area                  2
15  Super built-up  Area                  3
16  Super built-up  Area                  3
17  Super built-up  Area                  3
18  Super built-up  Area                  3
19  Super built-up  Area                  3


# IMAGE Processing

In [ ]:
from PIL import Image
#pip install pillow
img = Image.open("tajmahal.jpg")
#im = im.rotate(30)
img_size = img.size
print(img.format)
print(img_size)
print(img.mode)
img = img.convert("L")


FileNotFoundError: ignored

In [ ]:
!pip install nltk
!pip install scikit-learn

## **Tokens**

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.tokenize import RegexpTokenizer

text = "Hi !! my name is arushi. I am a datascience expert."
tokens = word_tokenize(text)
print(tokens)

['Hi', '!', '!', 'my', 'name', 'is', 'arushi', '.', 'I', 'am', 'a', 'datascience', 'expert', '.']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


# **Punctuation**

In [ ]:
from nltk.tokenize import RegexpTokenizer

text = "Hi !! my name is arushi. I am a datascience expert."
tokenizer = RegexpTokenizer(r'\w+')
tokens = tokenizer.tokenize(text)

print(tokens)

['Hi', 'my', 'name', 'is', 'arushi', 'I', 'am', 'a', 'datascience', 'expert']


# **Removing Stop words**

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso

import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

df = pd.read_csv("boston.csv")
X = df.drop(['CRIM'],axis=1)
y = df['CRIM']

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

LR = LinearRegression()
ridge = Ridge(alpha=1)
lasso = Lasso(alpha=1)

LR.fit(x_train,y_train)
ridge.fit(x_train.values,y_train.values)
lasso.fit(x_train.values,y_train.values)

print("Coeffi and Intercept LR: ",LR.coef_,LR.intercept_)
print("Coeffi and Intercept Ridge: ",ridge.coef_,ridge.intercept_)
print("Coeffi and Intercept Lasso: ",lasso.coef_,lasso.intercept_)


prediction1 = LR.predict(x_train)
prediction2 = ridge.predict(x_train.values)
prediction3 = lasso.predict(x_train.values)

print("mean square error LR: ",mean_squared_error(y_train,prediction1))
print("mean square error Ridge: ",mean_squared_error(y_train,prediction2))
print("mean square error Lasso: ",mean_squared_error(y_train,prediction3))


print("R2 LR: ",r2_score(y_train,prediction1))
print("R2 Ridge: ",r2_score(y_train,prediction2))
print("R2 Lasso: ",r2_score(y_train,prediction3))


print("********Test**************")

prediction1 = LR.predict(x_test)
prediction2 = ridge.predict(x_test.values)
prediction3 = lasso.predict(x_test.values)

print("mean square error LR: ",mean_squared_error(y_test,prediction1))
print("mean square error Ridge: ",mean_squared_error(y_test,prediction2))
print("mean square error Lasso: ",mean_squared_error(y_test,prediction3))


print("R2 LR: ",r2_score(y_test,prediction1))
print("R2 Ridge: ",r2_score(y_test,prediction2))
print("R2 Lasso: ",r2_score(y_test,prediction3))




In [ ]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso

import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

df = pd.read_csv("Real estate.csv")

X=df.drop(['Y house price of unit area'],axis=1)
Y=df['Y house price of unit area']

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)
LR = LinearRegression()
LR.fit(x_train,y_train)
predict_train = LR.predict(x_train)

print("Error in training: ",mean_squared_error(y_train,predict_train))
print("R2 values: ",r2_score(y_train,predict_train))

predict_test = LR.predict(x_test)
print("Error in testing: ",mean_squared_error(y_test,predict_test))
print("R2 values while testing: ",r2_score(y_test,predict_test))
