<a href="https://colab.research.google.com/github/Bavitayadav8/Bavitayadav8/blob/main/IIT_madras_%2C_Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

part 1

Aim: Revisiting the numpy
Details: One feature of NumPy that is powerful but tricky is the ability to perform
broadcasting, which really just refers to repeatedly performing an operation over one or more
dimensions.

Tasks:

In [ ]:
import numpy as np

1.The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [ ]:
A=np.arange(1,10)
print(A)


[1 2 3 4 5 6 7 8 9]


In [ ]:
A=np.arange(1,10).reshape(3,3) + 1
print(A)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


2. Now, create a 10 × 10 matrix A in which A[i][j] = i + j. You’ll be able to do this using
the vector you just created, and adding it to a reshaped version of itself.

In [ ]:
A = np.arange(1,101)
print(A)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
A = A + A.reshape(-1,1)
print(A)

[[  2   3   4 ...  99 100 101]
 [  3   4   5 ... 100 101 102]
 [  4   5   6 ... 101 102 103]
 ...
 [ 99 100 101 ... 196 197 198]
 [100 101 102 ... 197 198 199]
 [101 102 103 ... 198 199 200]]


3. A very common use of broadcasting is to standardize data, i.e., to make it have zero
mean and unit variance.
a. First, create a fake “data set” with 50 examples, each with five dimensions.
b. import numpy.random as npr
data = np.exp ( npr.randn(50, 5) )
c. Don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number
generation library, then generates a 50 × 5 matrix of standard normal random
variates and exponentiates them. The effect of this is to have a pretend data
set of 50 independent and identically-distributed vectors from a log-normal
distribution.

In [ ]:
import pandas as pd
from google.colab import files 
import io
file = files.upload()

Saving data.csv to data (1).csv


In [ ]:
df=pd.read_csv("data.csv")

In [ ]:
df.head(50)

area_type   availability                  location       size  \
0   Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1             Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2         Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3   Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4   Super built-up  Area  Ready To Move                  Kothanur      2 BHK   
5   Super built-up  Area  Ready To Move                Whitefield      2 BHK   
6   Super built-up  Area         18-May          Old Airport Road      4 BHK   
7   Super built-up  Area  Ready To Move              Rajaji Nagar      4 BHK   
8   Super built-up  Area  Ready To Move              Marathahalli      3 BHK   
9             Plot  Area  Ready To Move              Gandhi Bazar  6 Bedroom   
10  Super built-up  Area         18-Feb                Whitefield      3 BHK   
11            Plot  Area  Ready To Move                Whitefield  4 Bedroom   
12  Super built-up  Area  Ready To Move        7th Phase JP Nagar      2 BHK   
13        Built-up  Area  Ready To Move                 Gottigere      2 BHK   
14            Plot  Area  Ready To Move                  Sarjapur  3 Bedroom   
15  Super built-up  Area  Ready To Move               Mysore Road      2 BHK   
16  Super built-up  Area  Ready To Move             Bisuvanahalli      3 BHK   
17  Super built-up  Area  Ready To Move     Raja Rajeshwari Nagar      3 BHK   
18  Super built-up  Area  Ready To Move     Ramakrishnappa Layout      3 BHK   
19  Super built-up  Area  Ready To Move        Manayata Tech Park      2 BHK   
20        Built-up  Area  Ready To Move                   Kengeri      1 BHK   
21  Super built-up  Area         19-Dec                Binny Pete      3 BHK   
22            Plot  Area  Ready To Move               Thanisandra  4 Bedroom   
23  Super built-up  Area  Ready To Move                 Bellandur      3 BHK   
24  Super built-up  Area         18-Nov               Thanisandra       1 RK   
25  Super built-up  Area         18-May           Mangammanapalya      3 BHK   
26  Super built-up  Area  Ready To Move           Electronic City      2 BHK   
27        Built-up  Area         20-Dec                Whitefield      3 BHK   
28  Super built-up  Area         17-Oct          Ramagondanahalli      2 BHK   
29  Super built-up  Area  Ready To Move           Electronic City      3 BHK   
30  Super built-up  Area         19-Dec                 Yelahanka      4 BHK   
31  Super built-up  Area  Ready To Move             Bisuvanahalli      3 BHK   
32  Super built-up  Area  Ready To Move                    Hebbal      3 BHK   
33  Super built-up  Area  Ready To Move     Raja Rajeshwari Nagar      3 BHK   
34        Built-up  Area  Ready To Move             Kasturi Nagar      3 BHK   
35  Super built-up  Area         21-Dec            Kanakpura Road      2 BHK   
36  Super built-up  Area  Ready To Move  Electronics City Phase 1      2 BHK   
37  Super built-up  Area  Ready To Move              Kundalahalli      3 BHK   
38  Super built-up  Area  Ready To Move            Chikkalasandra      3 BHK   
39        Built-up  Area  Ready To Move               Uttarahalli      2 BHK   
40        Built-up  Area  Ready To Move             Murugeshpalya      2 BHK   
41  Super built-up  Area         19-Dec            Sarjapur  Road      3 BHK   
42  Super built-up  Area  Ready To Move               Ganga Nagar      1 BHK   
43            Plot  Area  Ready To Move                 Yelahanka  1 Bedroom   
44  Super built-up  Area         19-Sep            Kanakpura Road      2 BHK   
45            Plot  Area  Ready To Move                HSR Layout  8 Bedroom   
46  Super built-up  Area  Ready To Move              Doddathoguru      2 BHK   
47  Super built-up  Area         20-Sep                Whitefield      2 BHK   
48            Plot  Area  Ready To Move                  KR Puram  2 Bedroom   
49        Built

In [ ]:
import numpy.random as npr

In [ ]:
data = np.exp(npr.randn(50,5))
print(data)

[[ 1.39421853  1.06726315  1.50717043  1.06064034  5.07174636]
 [ 1.48887377  0.71954858  3.11629878  2.27422236  1.90069644]
 [ 1.60970085  0.27777463  3.37764378  3.51822107  0.64641397]
 [ 3.05255324  0.28232006  0.41620273  0.73580516  0.44754532]
 [ 0.18011362  1.10451462  2.76863754  2.93580696  0.49894676]
 [ 4.38607633  5.29330038  8.06071586  0.63811989  1.09467129]
 [ 0.82844314  1.01408974  0.66547936  0.17483053  1.82262156]
 [ 0.41188892  1.87891189  0.72387461  1.36643068  3.10885331]
 [ 1.09211875  0.82905741  2.19956227  0.63109743  0.44665919]
 [ 4.80719816  0.70678307  1.84482615  2.02807026  0.86019024]
 [ 0.54490455  2.1344443   4.15253316  0.03523702  1.36671942]
 [ 1.38652833  0.4702552   5.25886896  0.92424466  2.47914085]
 [ 1.09774682  0.09383613  3.45126324  0.45286079  1.51312753]
 [ 0.48260662  0.58469294  1.4215337   0.81624077  1.0923396 ]
 [ 0.2019797   0.19627455  1.60397553  2.7722219   1.63224072]
 [ 1.47545182  1.40049988  0.83952201  0.50892213  1.05

4. Now, compute the mean and standard deviation of each column. This should result in
two vectors of length 5. You’ll need to think a little bit about how to use the axis
argument to mean and std. Store these vectors into variables and print both of them.

In [ ]:
mean = np.mean(data, axis = 0)
print(mean)

[1.41423093 1.35294599 2.48902789 1.93744339 1.77567342]


In [ ]:
std = np.std(data, axis = 0)
print(std)

[1.24464471 1.45179691 2.15778882 2.48145348 1.910243  ]


5. Now standardize the data matrix by 1) subtracting the mean off of each column, and
2) dividing each column by its standard deviation. Do this via broadcasting, and store
the result in a matrix called normalized. To verify that you successfully did it, compute
the mean and standard deviation of the columns of normalized and print them out.

In [ ]:
normalized = (data - mean) / std
print(normalized)

[[-0.01607881 -0.19677879 -0.45502945 -0.35334253  1.72547312]
 [ 0.0599712  -0.43628513  0.29070078  0.13571843  0.06544875]
 [ 0.15704877 -0.74057973  0.41181782  0.637037   -0.5911601 ]
 [ 1.31629718 -0.73744883 -0.96062467 -0.48424773 -0.69526657]
 [-0.99154185 -0.17111992  0.12958156  0.40233016 -0.66835825]
 [ 2.38770581  2.71412231  2.58212849 -0.52361388 -0.35650026]
 [-0.47064659 -0.23340472 -0.84510055 -0.71031469  0.02457705]
 [-0.80532381  0.36228614 -0.81803801 -0.23011219  0.69791115]
 [-0.2587985  -0.36085528 -0.13414919 -0.52644386 -0.69573045]
 [ 2.72605283 -0.44507804 -0.29854717  0.03652169 -0.47924959]
 [-0.69845344  0.53829726  0.77093053 -0.76656943 -0.2140848 ]
 [-0.02225743 -0.60799881  1.28364789 -0.40830857  0.36826071]
 [-0.25427667 -0.86727686  0.44593583 -0.59827138 -0.13744109]
 [-0.74850623 -0.52917392 -0.49471671 -0.45183302 -0.35772088]
 [-0.97397371 -0.79671711 -0.41016635  0.33640708 -0.0750861 ]
 [ 0.04918744  0.03275519 -0.76444268 -0.57567924 -0.37

Aim: Performing the Hypothesis testing using the Chi-squared test


The table below is a survey response to 4 categorical variables: people in categories from
18–29, 30–44, 45–64 and >65 years, and their movie genre inclination, which is
“Action/Adventure”, “Romance” and “Biography”. Is there any evidence of a relationship
between the age group and their movie genre inclination, at 5% significance level?

              Action/Adventure      Romance       Biography        Total

    18-29        141                 68            4                213
    30-44        179                 159           7                345
    45-64        220                 216           4                440
    65&older     86                  101           4                191
    Total        626                 544           19               1189

Ans -->    significance = 5%
                 α = 5/100 =0.05
       degree of freedom = (r-1)(c-1)
        no. if row = 4
        no. of column = 3
        df= (4-1)(3-1)
        df= 6
        
         χ^2 = ∑(O-E)^2/E
          O= observe value
          E = expected value
 
   expected frequency = (taol row * total column)/N
                      = 213*626/1186
                      = 112.1

          Action/Adventure     Romance     Biography 
    18-29      E(112.1)        E(97.4)     E(3.4)
    30-44      E(181.1)        E(157.8)    E(5.5)
    45-64      E(231.6)        E(201.3)    E(7.0)
    65&older   E(100.5)        E(87.3)     E(3.0)  
    
     χ^2 =  ∑(O-E)^2/E
     χ^2 = (141-112.1)^2/112.1 + (68-97.4)^2/97.4 + (4-3.4)^2/3.4 +
           (179-181.6)^2/181.6 + (159-157.8)^2/157.8 + (7-5.5)^2/5.5 +
           (220-231.6)^2/231.6 + (216-201.3)^2/201.3 + (4-7.0)^2/7.0 +
           (86-100.5)^2/100.5 + (101-87.3)^2/87.3 + (4-3.0)^2/3.0

      χ^2 = 7.45 + 8.87 + 0.10 + 0.03 + 0.009  
           + 0.40 + 0.58 + 1.07 + 1.28 + 2.09 
      
       χ^2 = 21.8
       We reject H0 because 21.8 >= 12.59. We have statistically significant evidence at α =0.05 to show that H0 is false or that living arrangement and exercise are not independent  p =< 0.005.  

