<a href="https://colab.research.google.com/github/Bavitayadav8/Bavitayadav8/blob/main/KNN_Assignment13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Social_Networks_Ads.csv

**Importing the libraries**

In [29]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from scipy.spatial import distance
import matplotlib.pyplot as plt

In [30]:
import pandas as pd
import numpy as np


**Importing the dataset**

In [31]:
df = pd.read_csv("/content/Data (1).csv")

In [32]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

**Splitting the dataset into the Training set and Test set**

In [33]:
from sklearn.model_selection import train_test_split

x = df.drop(['Age'], axis = 1)
y = df['Salary']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)



**Feature Scaling**

In [35]:



#x = df.iloc[:, 1:3]
#print ("\nOriginal data values : \n",  x)
  
  
from sklearn import preprocessing
  
""" MIN MAX SCALER """
  
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))
  
# Scaled feature
x_after_min_max_scaler = min_max_scaler.fit_transform(x)
  
print ("\nAfter min max Scaling : \n", x_after_min_max_scaler)

Standardisation = preprocessing.StandardScaler()
  
# Scaled feature
x_after_Standardisation = Standardisation.fit_transform(x)
  
print ("\nAfter Standardisation : \n", x_after_Standardisation)
  


After min max Scaling : 
 [[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739        nan]
 [0.34782609 0.28571429]
 [       nan 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]]

After Standardisation : 
 [[ 0.71993143  0.71101276]
 [-1.62367514 -1.36437583]
 [-1.21009751 -0.84552869]
 [-0.10722383 -0.24020701]
 [ 0.16849459         nan]
 [-0.52080146 -0.49963059]
 [        nan -1.01847774]
 [ 1.27136827  1.31633443]
 [ 1.54708669  1.66223253]
 [-0.24508304  0.27864014]]


**Fitting K-NN to the Training set**

In [44]:
df= pd.read_csv("/content/Data (1).csv")
df= df.dropna()
(df['Salary'].unique())


x= df[['Age']]
y= df['Salary']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3)

knn = KNeighborsClassifier(n_neighbors= 3)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

**Predicting the Test set results**

In [46]:
prediction = knn.predict(x_test)
print(prediction)

[48000. 67000. 58000.]


**Making the Confusion Matrix**

In [51]:
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.svm import SVC

In [52]:
df= df.dropna()
x=df[['Age']]
y=df['Salary']

model = SVC()
model.fit(x,y)
predicted = model.predict(x)

print(classification_report(y,predicted))

              precision    recall  f1-score   support

     48000.0       1.00      1.00      1.00         1
     54000.0       1.00      1.00      1.00         1
     58000.0       1.00      1.00      1.00         1
     61000.0       1.00      1.00      1.00         1
     67000.0       1.00      1.00      1.00         1
     72000.0       1.00      1.00      1.00         1
     79000.0       1.00      1.00      1.00         1
     83000.0       1.00      1.00      1.00         1

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

